title: kaifischer.github.io

author: 
    name: Kai Fischer
    email: str('kaifabi')+'@'+'.'.join(['posteo','net'])

description: >- # this means to ignore newlines until "baseurl:"
    Thoughts from former stardust.

show_excerpts: false

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kaifabi.github.io" # the base hostname & protocol for your site
github_username: kaifischer
twitter_username: eigenkai

minima:
    date_format: "%b %-d, %Y"
    social_links:
        twitter: eigenkai 
        github: kaifischer

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

kramdown:
    auto_ids: true
