title: kaifishr.github.io

author: 
    name:
    email:

description: >- # this means to ignore newlines until "baseurl:"
    Thoughts from former stardust.

show_excerpts: false

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kaifishr.github.io" # the base hostname & protocol for your site
github_username: kaifisher
twitter_username: fishrkai

minima:
    date_format: "%b %-d, %Y"
    social_links:
        twitter: fishrkai
        github: kaifishr

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

kramdown:
    auto_ids: true

google_verify: IcZuM-x73Es42UnsnJ0Mww-_B4vBKo4LCEHnx6bt7l8
google_analytics: G-HB9KBW3EXD
